apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: ProspectPilot DB
    uid: ppdb
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: prospectpilot
    secureJsonData:
      password: prospectpilot
    jsonData:
      database: prospectpilot
      sslmode: disable
      postgresVersion: 1600
